# Generated by Django 6.1 on 2026-09-04 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_trip_number_of_people_day_weather_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Transport', 'Transport'), ('Accommodation', 'Accommodation'), ('Food', 'Food'), ('Activities', 'Activities'), ('Other', 'Other')], default='Other', max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='trips.trip')),
            ],
        ),
    ]
