# Generated by Django 6.1 on 2026-09-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='budget_alert',
            field=models.TextField(blank=True, null=True),
        ),
    ]
