# Generated by Django 6.1 on 2026-09-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_trip_budget_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.CharField(default='Induwari', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='split_among',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
